### ISSUE TITLE
Strategy for managing GitHub API rate limits

### ISSUE THREAD

**Issue by howardroark** [codingcoop/gitsup#10]
So the current github api as a rate limit that may prevent too much browsing.   Need a strategy to deal with this.

Here is the API rate limit rules...

https://developer.github.com/v3/#rate-limiting

**Comment by howardroark** [comment]
For a start add a message to indicate that the rate limit has been reached.

**Comment by mariosant** [comment]
[I figured out](https://developer.github.com/guides/getting-started/) that the limit for non authenticated api calls are about 60 per hour, while authenticated calls can make up to 5000 per hour.

**Comment by howardroark** [comment]
So would that mean that after Oauth a token can be used to allow 5000?  If so the solution is really just to say  "Please sign in to browse more".

**Comment by mariosant** [comment]
Yup :)  

Marios Antonoudiou  
[@marios_ant](https://link.nylas.com/link/81lrgg7ecvlxe311aeil15h4o/3b6efe31f3
454dd38fa3f9e936145c46/0?redirect=https%3A%2F%2Ftwitter.com%2Fmarios_ant)

![](https://link.nylas.com/open/81lrgg7ecvlxe311aeil15h4o/6edaad13217f4d3dab9b
75ac66469371)

**Comment by howardroark** [comment]
This is complete on `release` in basic form.  The strategy is in place never the less :)

**Comment by mariosant** [comment]
It's great to figure out how to do it! This should be added into the `development` branch once we move to components.

**Comment by howardroark** [comment]
Yeah, I'll post the commit for reference... https://github.com/gitsup/gitsup/commit/a9eb93bc17fcb99507e1977148012b4ba7dbbe90

Basically I just assume `403` status means rate limit.

Should we reopen?

**Comment by mariosant** [comment]
I guess we should, until this gets fixed in `development`.
