### ISSUE TITLE
Integrating with github reactions once they are available through the API

### ISSUE THREAD

**Issue by capaj** [codingcoop/gitsup#13]
This is a future issue, because currently reactions are not included in the API responses, but I think they will be.

If you haven't noticed reactions yet, read: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

That is nice, because the actual vote counts can be saved in github and all gitsup needs to do is keep a ledger.

**Comment by howardroark** [comment]
Was just talking about the same thing today!  100% agree that it should be explored when the data gets into the API.  I'm gonna up vote this on gitsup.com ;)

**Comment by howardroark** [comment]
This is done :)  The app is now just a way to visualize issues sorted by "up votes".  At least as a new starting point ;)

**Comment by howardroark** [comment]
Here is a good example... https://gitsup.herokuapp.com/isaacs/github  ... still need to move data caching to the server and speed things up with pagination.
