### ISSUE TITLE
Issue with voted issues not alway sorting correctly.

### ISSUE THREAD

**Issue by howardroark** [codingcoop/gitsup#18]
There is an intermittent issue where issues with votes are not sorted correctly.

**Comment by made-by-chris** [comment]
can you describe how to reproduce this issue?

**Comment by howardroark** [comment]
It is intermittent but seems to happen when you load up the site in an "uncached" state for the first time.  Meaning at a point when the browser is doing a lot of work to get ready to run code.  If you reload after that it works fine.  It's very odd because the array is being sorted before it is rendered.

I just think I may be missing something obvious... you know?

**Comment by made-by-chris** [comment]
The code is never wrong :D

**Comment by howardroark** [comment]
The trick is shaking your assumptions about the code :P
