### ISSUE TITLE
Duplicate items in the list

### ISSUE THREAD

**Issue by gmile** [codingcoop/gitsup#26]
Each item appears three times, see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/207112/15959770/fb36c6a0-2f04-11e6-84ec-e2e6a18b9e0a.png)

**Comment by howardroark** [comment]
Thanks!  Yeah... the initial go had some wacky stuff going on.  I am now simplifying things as much as possible (in a meteor.js way).  Should be working better soon.  Feel free to poke around the code!
